// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251112124936_UpdateProductEntity")]
    partial class UpdateProductEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "1.jpeg",
                            Price = 32000.0,
                            ProductName = "Apple Iphone 10"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "2.jpeg",
                            Price = 42000.0,
                            ProductName = "Apple Iphone 11"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "3.jpeg",
                            Price = 52000.0,
                            ProductName = "Apple Iphone 12"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "4.jpeg",
                            Price = 62000.0,
                            ProductName = "Apple Iphone 13"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "5.jpeg",
                            Price = 72000.0,
                            ProductName = "Apple Iphone 14"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "6.jpeg",
                            Price = 82000.0,
                            ProductName = "Apple Iphone 15"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "7.jpeg",
                            Price = 92000.0,
                            ProductName = "Apple Iphone 16"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate iusto voluptatem similique cupiditate officiis expedita maxime nihil placeat ad, rem quis tenetur consequuntur quia praesentium odit ex vel id. Asperiores.",
                            Image = "8.jpeg",
                            Price = 102000.0,
                            ProductName = "Apple Iphone 17"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
