// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250831173618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Price = 32000.0,
                            ProductName = "Apple Iphone 12"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            Price = 42000.0,
                            ProductName = "Apple Iphone 13"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Price = 52000.0,
                            ProductName = "Apple Iphone 14"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Price = 62000.0,
                            ProductName = "Apple Iphone 15"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Price = 72000.0,
                            ProductName = "Apple Iphone 16"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Price = 82000.0,
                            ProductName = "Apple Iphone 17"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
